name: Refresh SSA Data

on:
  workflow_dispatch:
  schedule:
    - cron: '10 6 * 1-5 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install pandas requests lxml
      - run: python refresh_ssa_data.py
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Update SSA data" || exit 0
          git push
