name: source_data_refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '10 5 7,14,21,28 2,3,4 *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install pandas requests lxml
      - run: python source_data_refresh.py
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "annual_data_refresh - ${timestamp}" || exit 0
          git push
